### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by fernandonetom** [RealPeha/telegram-keyboard#14]
Hello, I'm trying to use the library and nodejs is returning the following error:

```js
/my-project/node_modules/telegram-keyboard/lib/keyboard.js:12
    static defaultOptions = {
                          ^

SyntaxError: Unexpected token =
```

I already searched a lot but I didn't find anything like that, do you know what it can be?

**Comment by fernandonetom** [comment]
I am using nvm to test compatibility of other projects with various versions of nodejs, when returning to version `12.8.1` it returned to work.

Do you know why it doesn't work in other versions when I use it for example: `nvm use 14`?

**Comment by RealPeha** [comment]
Hello @fernandonetom!

This is a public static field, which is most likely available since Node.js v14

Thanks a lot, I will add the required version number to package.json

**Comment by fernandonetom** [comment]
Hey @RealPeha, thank you for you answer!
