### ISSUE TITLE
[HW/FR] Add mobile phone/current location request with callback

### ISSUE THREAD

**Issue by mkikets99** [RealPeha/telegram-keyboard#16]
It will be very helpful if this plugin can ask a user for giving a phone number or current location.
Is it possible to implement this feature?

PS: HW - help wanted, FR - feature request

**Comment by RealPeha** [comment]
Yes, this is possible. You can use `Key.contact` and `Key.location` as key in buttons array
For example:
```js
const { Keyboard, Key } = require('telegram-keyboard')

Keyboard.make([
  Key.location('Send location')
]).reply()
```

**Comment by mkikets99** [comment]
There is one thing...
When i use `Key.contact` seems like Key is sent like simple key

```javascript
ctx.reply('Send me your number please', 
    Keyboard.make([
        Key.contact("📲 Send phone number")
    ]).oneTime(true).resize(true).reply()
);
```

Reply returns this:
```json
{
  "reply_markup": {
    "resize_keyboard": true,
    "one_time_keyboard": true,
    "keyboard": [ [ "📲 Send phone number" ] ]
  }
}
```

**Comment by mkikets99** [comment]
Yeah

https://github.com/RealPeha/telegram-keyboard/blob/cce91f1670c6aa8482da17d7b007d4d250e37228/lib/keyboard.js#L33

This functions destroys the `request_contact` and `hide` every single time

**Comment by mkikets99** [comment]
Waiting for fix, but my tempo solution to this is to change
https://github.com/RealPeha/telegram-keyboard/blob/cce91f1670c6aa8482da17d7b007d4d250e37228/lib/keyboard.js#L36
into this
```javascript
return button;
```
