### ISSUE TITLE
How to add one_time_keyboard field in Reply Keyboard 

### ISSUE THREAD

**Issue by nilesh-kawar** [RealPeha/telegram-keyboard#19]
I want to add `one_time_keyboard : true`  in Reply Keyboard.

**Comment by RealPeha** [comment]
You can add extra options like this:
```js
Keyboard.make(['Button']).reply({ one_time_keyboard: true })
// or
Keyboard.reply(['Button'], {}, { one_time_keyboard: true })
```

**Comment by nilesh-kawar** [comment]
@RealPeha 

I tried both ways but none of them is working.

1) `const keyboard = Keyboard.reply(['Button'], {}, { one_time_keyboard: true })`
2) `const keyboard = Keyboard.make(['Button']).reply({ one_time_keyboard: true })`

I console log the keyboard variable and I'm getting results like this:

```
{
  reply_markup: { 
        resize_keyboard: true, 
       keyboard: [ [Array] ] 
   },
  one_time_keyboard: true
}
```

So the problem is  `one_time_keyboard: true` should be inside `reply_markup` key.

**Comment by RealPeha** [comment]
Oh, exactly, inside `reply_markup` ... worked with this for a long time and already forgot. There are [special methods](https://github.com/RealPeha/telegram-keyboard/blob/master/lib/keyboard.js#L96) for properties that must be inside `reply_markup`

in your case you do like this:
```js
const keyboard = Keyboard.make(['Button']).oneTime().reply()
```
