### ISSUE TITLE
How to customize button text and reply

### ISSUE THREAD

**Issue by CryptoCarlos21** [RealPeha/telegram-keyboard#31]
I want the button title to be different to the reply it posts

**Comment by RealPeha** [comment]
Hi @CryptoCarlos21 
You should use `Key.callback` as button
Simple example:
```js
const { Keyboard, Key } = require('telegram-keyboard')

Keyboard.inline([
    Key.callback('Key title', 'answer')
])
```

But keep in mind this only works for inline keyboard

**Comment by CryptoCarlos21** [comment]
Thank you, it works, I'm customizing the messaging now. 

so if I have the following code, the bot replies with this. See the reply contains "/play" which is a group command. how can I make it that the bot sends this message as the user instead so it will trigger my other bot to play the track?

Right now I have 2 bots, 1 that plays music fine once users use the /play and a youtube url
This new bot I'm trying to have buttons instead of users having to manually type the command. So button 1 would be a track I configured 


`bot.hears('Audio Triggers', (ctx) => {
    const keyboard = Keyboard.make([
        [Key.callback('1st track', '/play https://www.youtube.com/watch?vxxxxxxx').inline()
    bot.on('callback_query', (ctx) => {
        return ctx.reply(ctx.callbackQuery.data)
    })
    return ctx.reply('All audio files', keyboard)
})`

**Comment by RealPeha** [comment]
You cannot make the bot send a message on behalf of the user
