### ISSUE TITLE
Limit access to admins only

### ISSUE THREAD

**Issue by CryptoCarlos21** [RealPeha/telegram-keyboard#32]
How to limit access so the buttons don't show up for all users.

Either only the user currently pressing the buttons or all admins?

**Comment by RealPeha** [comment]
you need to send different buttons for admin and for users
for example:
```js
if (admin) {
   ctx.reply('you are admin', Keyboard.reply(['Admin button']))
} else {
   ctx.reply('you are user', Keyboard.reply(['User button']))
}
```

**Comment by CryptoCarlos21** [comment]
Thank you, I tried it and i still the following issue:

- The bot will show the buttons to all users regardless of if they are admin or not
- The non admin users can click the buttons and the reply is given in the chat but no bot action is taken, it's ignored
- If the admin selects any buttons the non admins can see the button menu change in realtime too

How do I stop non admins from seeing the menu at all? or limiting it to the current user interacting with it only?

Here's my code:

```

const main = (ctx) => {
    if( ctx.from._is_in_admin_list ){
    return ctx.reply('Select your audio list', Keyboard.reply(['Treasure Chest Audio 1','Treasure Chest Audio 2','Treasure Chest Audio 3','Controls'], { columns: 3 }))
}
else {
}
}
```

```

bot.use(function(ctx, next){
	if( ctx.chat.id > 0 ) return next();
		return bot.telegram.getChatAdministrators(ctx.chat.id)
		.then(function(data){
			if( !data || !data.length ) return;
			console.log('admin list:', data);
			ctx.chat._admins = data;
			ctx.from._is_in_admin_list = data.some( adm => adm.user.id === ctx.from.id );
		})
		.catch(console.log)
		.then(_ => next(ctx));
});

bot.start(main)
bot.hears('Back', main)
```

```
bot.hears('Controls', (ctx) => {
    if( ctx.from._is_in_admin_list ){
    const keyboard = Keyboard.make(["/stop","/pause","/resume","/skip"], { columns: 2 })
    return ctx.reply('Controls menu selected', Keyboard.combine(keyboard, backKeyboard).reply())
}
else {
//do nothing
}
})

bot.launch()
```

**Comment by RealPeha** [comment]
I understand your bot works in groups. Well, in that case it seems to me that you cannot separate the buttons for the admin and for the users. But I'm not really very familiar with this, so I can't say for sure.
