### ISSUE TITLE
Cannot deploy to heroku

### ISSUE THREAD

**Issue by CryptoCarlos21** [RealPeha/telegram-keyboard#33]
I have this running fine locally but when i try to deploy to heroku the modules won't work.
Is there a different package.json configuration needed to work with heroku?

```2021-11-18T17:18:54.547748+00:00 app[web.1]: Error: Cannot find module 'telegraf'
2021-11-18T17:18:54.547748+00:00 app[web.1]: Require stack:
2021-11-18T17:18:54.547749+00:00 app[web.1]: - /app/index.js```

**Comment by RealPeha** [comment]
I do not think that this problem is related to this package, and since I have not deployed to heroku, then I can not advise anything
