### ISSUE TITLE
Buttons that open app on mobile

### ISSUE THREAD

**Issue by grunch** [RealPeha/telegram-keyboard#39]
Hi, I am not sure if this is the place to ask this, but if is not it would be great if you can help me clarifying this issue.

I have a telegram bot and I need to create a button that when the user tap on it it should open a mobile app, when I do this on a HTML site I add on an anchor tag this `href`

 ```
href = "lightning:lnbc60n1p3yyvn6pp5yx2eycreyxuxy048v4cf9305vmhtdhk23kxk0tp6xtd39r64mkcsdpl2pshjmt9de6zqen0wgsrvgrsd9ux2mrnypshggrnv96x7umgd9ejuurvv93k2tsxqzjccqpjsp5p9lyqyu3fskh9zzjldyq2zgdrmh9thzcjpr8zeun6hjk9sy99y5qrzjqfyyyppkypkukp3nrql8kektwzp6vcf4j9n7w8f8c5axh3me6ktsvzj0w5qqztcqqqqqqqryqqqqqqgq9q9qyyssqs0gspkcm8dqw2gh358yygjg8kav5rlg5u7d0rgejmqkc9k9t2xvq7p7pwu08ff3m275t39rdc9888vw8ht7hy8u883wcvcymvwe0tnsputm7w6"
```
I tried to do it on a inline button with `url` but it doesn't work.

**Comment by mkikets99** [comment]
As it said here:
https://stackoverflow.com/a/59523768/5779307

> The main answer is: Telegram doesn't allow to open external applications from bot and doesn't allow use any protocol in URI, except for http and tg.
>
>I think, you can use 3rd-party (or your one) service, which will redirect you on any page that you will ask. Your URL may be a URI to your app: your mobile/PC browser can redirect you directly to the app.

This means that its limited by Telegram itself from opening apps
